---
- hosts: all
  become: true

  pre_tasks:
    - name: vars
      include_vars: vars.yml

    - name: cache update
      import_tasks: pre_tasks/packages.yml

  tasks:
    - name: Download and verify the binary
      import_tasks: tasks/binary.yml

    - name: Set evn for gitea 
      import_tasks: tasks/env.yml