---
- name: Create a directory
  file:
    path: /home/{{ ansible_user }}/binary
    state: directory
    mode: "0755"

- name: Download gitea binary
  get_url:
    url: https://dl.gitea.io/gitea/{{ gitea_varsion }}/gitea-{{ gitea_varsion }}-linux-amd64
    dest: /home/{{ ansible_user }}/binary
    mode: 0775

- name: Download gitea asc file
  get_url:
    url: https://dl.gitea.io/gitea/{{ gitea_varsion }}/gitea-{{ gitea_varsion }}-linux-amd64.xz.asc
    dest: /home/{{ ansible_user }}/binary

- name: Check gitea gpg key status
  command: "gpg --list-keys 0x{{ gpg_key_gitea }}"
  register: gpg_key_gitea_status

- name: install gitea gpg key
  command: "gpg --keyserver {{ gpg_server_gitea }} --recv {{ gpg_key_gitea }}"
  register: _gitea_import_key
  when: gpg_key_gitea_status.rc != 0
