---
- name: Create a directory
  file:
    path: /home/{{ ansible_user }}/binary
    state: directory
    mode: "0755"

- name: Download gitea binary
  get_url:
    url: https://github.com/go-gitea/gitea/releases/download/v{{ gitea_varsion }}/gitea-{{ gitea_varsion }}-linux-amd64
    dest: /home/{{ ansible_user }}/binary
    mode: 0775

- name: Download gitea asc file
  get_url:
    url: https://github.com/go-gitea/gitea/releases/download/v{{ gitea_varsion }}/gitea-{{ gitea_varsion }}-linux-amd64.asc
    dest: /home/{{ ansible_user }}/binary

- name: install gitea gpg key
  command: "gpg --keyserver {{ gpg_server_gitea }} --recv {{ gpg_key_gitea }}"
  register: gpg_install
  changed_when: gpg_install.rc != 0

- name: verify binary signature
  command: "gpg --verify /home/{{ ansible_user }}/binary/gitea-{{ gitea_varsion }}-linux-amd64.asc /home/{{ ansible_user }}/binary/gitea-{{ gitea_varsion }}-linux-amd64"
  changed_when: false
