---

- name: check binary exists
  stat: 
    path: /home/{{ ansible_user }}/binary/gitea
  register: binary_status  

- name: rename downloaded binary
  command: "cp /home/{{ ansible_user }}/binary/gitea-{{ gitea_varsion }}-linux-amd64 /home/{{ ansible_user }}/binary/gitea"
  changed_when: binary_status.stat.exists != true

- name: check binary in global location
  stat: 
    path: /usr/local/bin/gitea
  register: binary_global

- name: move binary to global location
  command: "cp /home/{{ ansible_user }}/binary/gitea /usr/local/bin/gitea"
  changed_when: binary_global.stat.exists != true and binary_status.stat.exists
