---

- name: reset the permissons for gitea
  file:
    path: /etc/gitea
    owner: root
    mode: '0750'

- name: gitea config permissons
  file:
    path: /etc/gitea/app.ini
    owner: root
    mode: '0640'
